name: telegram notify

on: [push]

env:
  TELEGRAM_CHAT_ID: ${{ env.TELEGRAM_CHAT_ID }}
  TELEGRAM_BOT_ID: ${{ env.TELEGRAM_BOT_ID }} 
  GITHUB_REPO: ${{ github.repository }}
  GITHUB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/
  GITHUB_ACTIONS_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_CHAT_ID }}
          token: ${{ env.TELEGRAM_BOT_ID }}
        run: |
          echo ${{ GITHUB.REPO }} >> intro.txt
          echo ${{ env.TELEGRAM_CHAT_ID }} > chat_id
          echo ${{ env.TELEGRAM_CHAT_ID }} > bot_id
          echo "Build%20DEVELOPMENT" > message
          echo "Log: ${{ env.GITHUB_ACTIONS_URL }}" >> log.txt
          chmod +x deployment/notify/success.sh
          ./deployment/notify/success.sh
